language: php
php:
- 5.6
env:
  global:
    secure: YE8u/4y62MPNhs4r4IXTtR2Lp4wb1tJocsMUemw+PHfvVNfeFUmLEGlK9TFdVvuLd+lnqARwr0E61GsFFEpayhr6VT8YI6N3dqhBtmNdYQSa1oS4krlDBRpjjydCgHoEP7WsUHOnaQGghcRXOBjNajlJwNBsIupHRUUP2kWR2Fg=
before_script:
- sudo apt-get install -y software-properties-common
- sudo apt-add-repository -y ppa:gviz-adm/graphviz-dev
- sudo apt-get update -qq
- sudo apt-get remove -y libcdt4
- sudo apt-get remove -y libpathplan4
- sudo apt-get install -y graphviz
- composer selfupdate --quiet
- composer install -n --prefer-source --dev
- mkdir -p build/docs
script:
- vendor/bin/phpdoc.php -d ./src -t ./build/docs
after_script:
- bash .travis_publish_doc.sh
