language: php
php:
- 5.6
env:
  global:
  - secure: i+bGFlCCxJ1jwW5FxtCdV7xt9KzAZs0ZjJOsCDvqTWWGF0oD/xGJH7f57vyLG7QwbQKJWIue8dhafKgs+8PAL3dijiiIWL+Qzyq3abmlvRoBt8qj5uu/369brWjBj9+TVjjYKDH3D1dWDqmNhovhSeDX41X2dSeuKR8PoTqCofZImD4jUKZDHIAmNntWhLZ29nSQkZjyuKUrEyJDs+UZJS2Hv9EaeX8fLYr2yBL9cz0BvgGwLqevsf7FS5VRuD4Qk0cXVFhublz5vx+3srvrC9nqxwJa4GtXMScllK/sITQG1XuYmDWpEDGzkjdpKkuM7nci1L1Lt+C7GvShl8F+Ga49NVOkdTyOk6OUsmI62qpnl1CUbwYZJG1F9gFG2U/G/9MwrGamu+C9xRiHjttEdbRGrTg04pZxeKVCKK0JfiV23r6VRzHj8Xc3u2Ja2MuFBcpNopeV4a9wKFKzUfnCume5VdeFTIXAHD1MmmZabhSncTw66YB8tX+O6xv73bXv0gIf3LHEaBg+/dIAUTHk88Ji4y6jkMfJtG3zHTgRz5j/amo8vDGWnVNPJEFV0y3w4UNsOhV5mxFvpQZIK2QjjmhzfkcXFGIEFR39Jp+dIQl15XCwTxXdgZL2eFZiy2paJLEdaqRKufpLriO7BwGW1OICtx6xYr0PQciog/A/u7k=
before_script:
- sudo apt-get install -y software-properties-common
- sudo apt-add-repository -y ppa:gviz-adm/graphviz-dev
- sudo apt-get update -qq
- sudo apt-get remove -y libcdt4
- sudo apt-get remove -y libpathplan4
- sudo apt-get install -y graphviz
- composer selfupdate --quiet
- composer install -n --prefer-source --dev
- mkdir -p build/docs
script:
- vendor/bin/phpdoc.php -d ./src -t ./build/docs
after_script:
- bash .travis_publish_doc.sh
